services:
  - name: job-seek-app
    type: web
    env: python
    rootDir: app/backend 
    buildCommand: |
      cd ../frontend && npm install && npm run build
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: "postgresql+asyncpg://username:password@hostname:port/dbname"
      - key: SECRET_KEY
        value: "your_secret_key"
